const {chromium} = require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES + '/playwright');
const path = require('path');
(async () => {
 const launchOptions = {headless:true, args:['--no-sandbox']};
 if (process.env.PLAYWRIGHT_EXECUTABLE_PATH) launchOptions.executablePath = process.env.PLAYWRIGHT_EXECUTABLE_PATH;
 const browser = await chromium.launch(launchOptions);
 const page = await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765/');
 await page.getByRole('button',{name:'＋ Tạo môn học mới'}).click();
 await page.locator('#new-course-name').fill('Kiến trúc hệ thống');
 await page.getByRole('button',{name:'Tạo không gian học tập'}).click();
 await page.locator('#course-dialog').waitFor({state:'hidden'});
 await page.locator('#document-input').setInputFiles(path.resolve('app/examples/course-notes.txt'));
 await page.locator('#document-list li').first().waitFor();
 await page.getByRole('button',{name:'Tạo thủ công ＋'}).click();
 await page.getByRole('button',{name:'Lưu rubric',exact:true}).click();
 await page.locator('#rubric-dialog').waitFor({state:'hidden'});
 await page.locator('#student-name').fill('Anh Nguyễn');
 await page.locator('#max-questions').fill('4');
 await page.screenshot({path:'qa/setup-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Bắt đầu phỏng vấn'}).click();
 await page.locator('#answer-input').waitFor({state:'visible'});
 await page.waitForFunction(()=>!document.getElementById('answer-input').disabled);
 for(let i=0;i<4;i++) {
   await page.locator('#answer-input').fill('Theo em, cache-aside đọc cache trước. Khi cache miss thì đọc database và ghi lại cache. TTL giúp giới hạn thời gian tồn tại nhưng vẫn có thể đọc dữ liệu cũ.');
   await page.getByRole('button',{name:'Gửi câu trả lời ↑'}).click();
   if(i<3) await page.waitForFunction(()=>!document.getElementById('answer-input').disabled);
   else await page.waitForFunction(()=>document.getElementById('chat-subtitle').textContent.includes('Chờ đánh giá'));
 }
 await page.screenshot({path:'qa/chat-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Kết thúc & xem đánh giá'}).click();
 await page.locator('#report-dialog').waitFor({state:'visible'});
 if(!await page.locator('#report-content').textContent().then(t=>t.includes('8'))) throw new Error('Missing score');
 await page.screenshot({path:'qa/report-desktop.png',fullPage:true});
 await page.locator('[data-close="report-dialog"]').click();
 await page.getByRole('button',{name:'03 Lịch sử & kết quả'}).click();
 await page.locator('.history-item').first().waitFor();
 await page.reload();
 await page.getByRole('button',{name:'03 Lịch sử & kết quả'}).click();
 await page.locator('.history-item').first().waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'01 Chuẩn bị buổi học'}).click();
 await page.screenshot({path:'qa/setup-mobile.png',fullPage:true});
 const overflow = await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
 console.log(JSON.stringify({errors, overflow, result:'create course > upload > rubric > 4-turn interview > report > history > reload: OK'}));
 await browser.close();
 if(errors.length || overflow) process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
