spring:
  datasource:
    url: ${DEV_DB_URL:jdbc:postgresql://ep-dry-block-b3yhbez5-pooler.c-4.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require}
    username: ${DEV_DB_USERNAME:neondb_owner}
    password: ${DEV_DB_PASSWORD:npg_P7CZhEKTy2Dp}

aives:
  ai:
    openai-api-key: ${OPENAI_API_KEY:}
    google-cloud-credentials: ${GOOGLE_APPLICATION_CREDENTIALS:}
  audio:
    mode: BUFFERED  # BUFFERED (default) or STREAMING
    storage-path: ./uploads/audio
